### ISSUE TITLE
Front page fails to render completely: Undefined index: carousel; Error: open() on null?

### ISSUE THREAD

**Issue by anthonyfok** [OpenDRR/riskprofiler#110]
With code + db export dated 2023-05-04:

```
[05-May-2023 09:58:43 UTC] PHP Notice:  Undefined index: carousel in /var/www/html/site/assets/themes/fw-parent/blocks/query/elements/query_items.php on line 38
[05-May-2023 09:58:43 UTC] PHP Fatal error:  Uncaught Error: Call to a member function open() on null in /var/www/html/site/assets/themes/fw-parent/blocks/query/elements/query_items.php:38
Stack trace:
#0 /var/www/html/site/assets/themes/fw-parent/blocks/content/query.php(235): include()
#1 /var/www/html/site/assets/themes/fw-parent/resources/functions/loop/extras.php(116): include('/var/www/html/s...')
#2 /var/www/html/site/assets/themes/fw-parent/resources/functions/loop/elements.php(792): block_output('open')
#3 /var/www/html/site/assets/themes/fw-parent/resources/functions/loop/elements.php(125): open_element(Array, 'field', 163)
#4 /var/www/html/site/assets/themes/fw-parent/resources/functions/loop/elements.php(85): content_loop('elements', 163, true)
#5 /var/www/html/site/assets/themes/fw-parent/template/layout.php(58): content_loop('elements', 2)
#6 /var/www/html/site/assets/themes/fw-parent/front-page.php(1): include('/var/www/html/s...')
#7 /var/www/html/site/wp-includes/template-loader.php(106): include('/var/www/html/s...')
#8 /var/www/html/s in /var/www/html/site/assets/themes/fw-parent/blocks/query/elements/query_items.php on line 38
```

This error is also preventing Simply Static export from working.

**Comment by anthonyfok** [comment]
Many thanks to @phil-evans for fixing the issue by updating the files and libraries in the h7-riskprofiler repo earlier today (2023-05-05).
